
/* Drop Tables */

DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE CNSLT_RESVE CASCADE CONSTRAINTS;
DROP TABLE FAQ CASCADE CONSTRAINTS;
DROP TABLE LAWYER_INFO CASCADE CONSTRAINTS;
DROP TABLE MBER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE CATEGORY
(
	CATEGORY_NM varchar2(10) NOT NULL,
	CATEGORY_DES varchar2(500),
	CATEGORY_ICON varchar2(100),
	PRIMARY KEY (CATEGORY_NM)
);


CREATE TABLE CNSLT_RESVE
(
	RESVE_DATE varchar2(10) NOT NULL,
	LAWYER_ID varchar2(20) NOT NULL,
	MBER_ID varchar2(20) NOT NULL,
	RESVE_SETLE_AT char NOT NULL,
	-- (예약신청 후 결제 전)결제대기
	-- (예약신청 후 결제 직후) 결제 완료
	-- (결제 후 예약 예정시간 이전)예약 대기중
	-- (예약시간 도래) 상담 진행중
	-- (예약시간 이 후) 상담 완료
	RESVE_SITTN char NOT NULL,
	RESVE_COST varchar2(8) NOT NULL,
	PRIMARY KEY (RESVE_DATE, LAWYER_ID, MBER_ID)
);


CREATE TABLE FAQ
(
	LAWYER_ID varchar2(20) NOT NULL,
	FAQ_SJ varchar2(100),
	FAQ_CN varchar2(1000)
);


CREATE TABLE LAWYER_INFO
(
	LAWYER_ID varchar2(20) NOT NULL,
	LAWYER_NM varchar2(30) NOT NULL,
	LAWYER_REALM varchar2(20) NOT NULL,
	LAWYER_CAREER varchar2(10) NOT NULL,
	LAWYER_QUALF varchar2(20) NOT NULL,
	LAWYER_ACDMCR varchar2(100) NOT NULL,
	LAWYER_ETC varchar2(300),
	LAWYER_ACCMLT varchar2(8) NOT NULL,
	LAWYER_ACCMLT_CO varchar2(5) NOT NULL,
	LAWYER_RECOMEND_CO varchar2(5) NOT NULL,
	LAWYER_COST varchar2(6),
	PRIMARY KEY (LAWYER_ID)
);


CREATE TABLE MBER
(
	MBER_ID varchar2(20) NOT NULL,
	MBER_TELNO varchar2(12) NOT NULL UNIQUE,
	MBER_EMAIL varchar2(50) NOT NULL UNIQUE,
	MBER_ADDR varchar2(80) NOT NULL,
	MBER_LEVEL char NOT NULL,
	MBER_AT char NOT NULL,
	MBER_NM varchar2(30) NOT NULL,
	PRIMARY KEY (MBER_ID)
);



/* Create Foreign Keys */

ALTER TABLE CNSLT_RESVE
	ADD FOREIGN KEY (LAWYER_ID)
	REFERENCES LAWYER_INFO (LAWYER_ID)
;


ALTER TABLE FAQ
	ADD FOREIGN KEY (LAWYER_ID)
	REFERENCES LAWYER_INFO (LAWYER_ID)
;


ALTER TABLE CNSLT_RESVE
	ADD FOREIGN KEY (MBER_ID)
	REFERENCES MBER (MBER_ID)
;


ALTER TABLE LAWYER_INFO
	ADD FOREIGN KEY (LAWYER_ID)
	REFERENCES MBER (MBER_ID)
;



/* Comments */

COMMENT ON COLUMN CNSLT_RESVE.RESVE_SITTN IS '(예약신청 후 결제 전)결제대기
(예약신청 후 결제 직후) 결제 완료
(결제 후 예약 예정시간 이전)예약 대기중
(예약시간 도래) 상담 진행중
(예약시간 이 후) 상담 완료';



